from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Protocol, Sequence


@dataclass(frozen=True, slots=True)
class Locator:
    by: Literal["css", "xpath", "name", "id", "tag"]
    value: str


class BrowserPort(Protocol):
    """Browser operations exposed to portal connectors.

    Connectors depend on this protocol, not on Selenium/WebElement directly.
    """

    def navigate(self, url: str) -> None: ...
    def page_ready(self) -> None: ...
    def click(self, locator: Locator, *, timeout: float | None = None) -> None: ...
    def fill(self, locator: Locator, value: str, *, timeout: float | None = None) -> None: ...
    def select_value(self, locator: Locator, value: str, *, timeout: float | None = None) -> None: ...
    def select_first_containing_option(
        self, scope: Locator, option_value: str, *, timeout: float | None = None
    ) -> bool: ...
    def read_value(self, locator: Locator, *, timeout: float | None = None) -> str: ...
    def read_text(self, locator: Locator, *, timeout: float | None = None) -> str: ...
    def read_attribute(
        self, locator: Locator, name: str, *, timeout: float | None = None
    ) -> str: ...
    def exists(self, locator: Locator, *, timeout: float = 2.0) -> bool: ...
    def wait_absent(self, locator: Locator, *, timeout: float | None = None) -> None: ...
    def upload(self, locator: Locator, path: str | Path, *, timeout: float | None = None) -> None: ...
    def confirm(self, labels: Sequence[str], *, timeout: float = 5.0) -> bool: ...
    def last_row_cells(self, table_body: Locator) -> list[str]: ...
    def execute_script(self, script: str, *args): ...
    def window_handles(self) -> list[str]: ...
    def current_window(self) -> str | None: ...
    def switch_window(self, handle: str) -> None: ...
    def close_window(self) -> None: ...
    def print_pdf(self, destination: str | Path) -> Path: ...
