from __future__ import annotations

from typing import Protocol

from workflow_ai.domain.models import Job, StepStatus


class JobRepository(Protocol):
    def create(self, job: Job) -> Job: ...
    def get(self, job_id: str) -> Job | None: ...
    def list(self, limit: int = 100) -> list[Job]: ...
    def find_existing_by_idempotency(self, key: str) -> Job | None: ...
    def update(self, job: Job) -> None: ...
    def claim_next(self, agent_id: str) -> Job | None: ...
    def record_step(
        self,
        job_id: str,
        step_name: str,
        status: StepStatus,
        message: str = "",
    ) -> None: ...
    def completed_steps(self, job_id: str) -> set[str]: ...
